import { useState } from "react";
import { generateTicketNumber } from "../utils/ticketHelpers";
import { supabase } from "../supabaseClient";

/**
 * useTicketForm — A reusable custom hook for any ticket submission form.
 *
 * HOW TO USE IN ANY PAGE:
 *   const { form, errors, submitted, ticketNumber, handleChange, handleSubmit, handleReset }
 *     = useTicketForm(initialFields, validationRules);
 *
 * @param {Object} initialFields   - The initial empty state of your form fields.
 * @param {Function} validateFn    - A function that receives the form and returns an errors object.
 * @param {string} ticketPrefix    - Prefix for the generated ticket number (e.g. "REG", "IT", "LIB").
 */
export function useTicketForm(initialFields, validateFn, ticketPrefix = "TKT") {
  const [form, setForm] = useState(initialFields);
  const [errors, setErrors] = useState({});
  const [submitted, setSubmitted] = useState(false);
  const [ticketNumber, setTicketNumber] = useState("");

  /**
   * handleChange — Returns a change handler for a specific field.
   * Usage in JSX: onChange={handleChange("fieldName")}
   */
  const handleChange = (field) => (e) => {
    setForm((prev) => ({ ...prev, [field]: e.target.value }));
    // Clear the error for this field as soon as the user starts typing
    setErrors((prev) => ({ ...prev, [field]: undefined }));
  };

  /**
   * handleSubmit — Runs validation. If valid, generates a ticket number and marks as submitted.
   */
  const handleSubmit = async () => {
    // 1. Validate first — same as before
    const validationErrors = validateFn(form);
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }

    setLoading(true);

    // 2. Save to Supabase
    const { data, error } = await supabase
      .from("tickets")
      .insert({
        student_id: "00000000-0000-0000-0000-000000000000", // temporary
        full_name: form.fullName, // 👈 add this
        category: "document_request",
        subject: form.subject,
        description: form.description,
        document_type: form.documentType,
        priority: "normal",
      })
      .select()
      .single();

    setLoading(false);

    if (error) {
      console.error("Supabase error:", error.message);
      setErrors({ submit: "Failed to submit. Please try again." });
      return;
    }

    // 3. Use the real ticket_number from the database (generated by your DB trigger)
    setTicketNumber(data.ticket_number);
    setSubmitted(true);
  };
  /**
   * handleReset — Clears everything back to the initial state.
   */
  const handleReset = () => {
    setForm(initialFields);
    setErrors({});
    setSubmitted(false);
    setTicketNumber("");
  };

  return {
    form,
    errors,
    submitted,
    ticketNumber,
    handleChange,
    handleSubmit,
    handleReset,
  };
}
