using System;

namespace BackendTicketEase.Models
{
    /// <summary>
    /// Represents a ticket submitted by a student.
    /// Maps to the 'tickets' table in the database.
    /// </summary>
    public class Ticket
    {
        // ── Identity ────────────────────────────────────────────
        public Guid Id { get; set; }

        /// <summary>
        /// Human-readable ticket ID. Auto-generated by the database.
        /// Example: TKT-2024-0001
        /// </summary>
        public string TicketNumber { get; set; } = string.Empty;

        // ── Ownership ───────────────────────────────────────────

        /// <summary>
        /// The student who submitted this ticket.
        /// </summary>
        public Guid StudentId { get; set; }

        /// <summary>
        /// The admin or staff assigned to handle this ticket.
        /// Null if not yet assigned.
        /// </summary>
        public Guid? AssignedTo { get; set; }

        // ── Request Details ─────────────────────────────────────

        /// <summary>
        /// Type of request.
        /// Allowed values: "document_request", "inquiry", "other"
        /// </summary>
        public string Category { get; set; } = string.Empty;

        public string Subject { get; set; } = string.Empty;

        public string Description { get; set; } = string.Empty;

        // ── Document Request Fields (optional) ──────────────────

        /// <summary>
        /// Only filled when Category = "document_request".
        /// Example: "Transcript of Records", "Enrollment Certificate"
        /// </summary>
        public string? DocumentType { get; set; }

        /// <summary>
        /// Reason the student needs the document.
        /// Only filled when Category = "document_request".
        /// </summary>
        public string? Purpose { get; set; }

        // ── Lifecycle ───────────────────────────────────────────

        /// <summary>
        /// Current status of the ticket.
        /// Allowed values: "open", "in_progress", "resolved", "rejected", "closed"
        /// Default: "open"
        /// </summary>
        public string Status { get; set; } = "open";

        /// <summary>
        /// Priority level of the ticket.
        /// Allowed values: "low", "normal", "high", "urgent"
        /// Default: "normal"
        /// </summary>
        public string Priority { get; set; } = "normal";

        // ── Timestamps ──────────────────────────────────────────
        public DateTime SubmittedAt { get; set; } = DateTime.UtcNow;
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Set when the ticket status changes to "resolved".
        /// </summary>
        public DateTime? ResolvedAt { get; set; }

        /// <summary>
        /// Set when the ticket status changes to "closed".
        /// </summary>
        public DateTime? ClosedAt { get; set; }

        // ── Navigation Properties ────────────────────────────────
        // Uncomment these if you are using an ORM like Entity Framework.

        // public Profile Student { get; set; }
        // public Profile? AssignedAdmin { get; set; }
        // public ICollection<TicketComment> Comments { get; set; }
        // public ICollection<TicketAttachment> Attachments { get; set; }
    }

    // ── Allowed Value Constants ──────────────────────────────────
    // Use these instead of hardcoding strings in your app logic.

    public static class TicketCategory
    {
        public const string DocumentRequest = "document_request";
        public const string Inquiry         = "inquiry";
        public const string Other           = "other";
    }

    public static class TicketStatus
    {
        public const string Open       = "open";
        public const string InProgress = "in_progress";
        public const string Resolved   = "resolved";
        public const string Rejected   = "rejected";
        public const string Closed     = "closed";
    }

    public static class TicketPriority
    {
        public const string Low    = "low";
        public const string Normal = "normal";
        public const string High   = "high";
        public const string Urgent = "urgent";
    }
}