name: Fullstack CI/CD

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - features/*
      - error/*
      - modify/*

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ticketEase-frontend/frontend-ticketEase

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm run build

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ticketEase-backend/BackendTicketEase

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore

      - run: dotnet build --configuration Release

      - run: dotnet test